version: 2.1
jobs:
  build:
    docker:
      - image: node:15.13.0
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Running Jest tests
          command: npm test
      - run:
          name: Running Cucumber tests
          command: npm run cucumber
workflows:
  run-build:
    jobs:
      - build
